@startuml

rectangle "单机数据系统" {
    [LocalFS单机存储]
    [SQL单机计算]
}

rectangle "Hadoop(基于磁盘的计算)" {
    package "HadoopCore" {
        [HDFS分布式文件系统]
        [MapReduce分布式计算框架]
        [Yarn资源管理和任务调度]
    }

    package "HadoopSql" {
        [Hive]
        [Impala]
        [Presto]
    }
}

rectangle "Spark(基于内存的计算)" {
    [SparkCore]
    [SparkSql]
    [SparkStreaming]
    [SparkMLlib]
    [SparkGraphX]
}

[LocalFS单机存储]-->[HDFS分布式文件系统]:一台机器存不下
[SQL单机计算]-->[MapReduce分布式计算框架]:一台机器算太慢
[SQL单机计算]-->[SparkCore]:一台机器算太慢

[MapReduce分布式计算框架]-->[Hive]:不想写MR程序，只想写SQL
[Yarn资源管理和任务调度]-->[MapReduce分布式计算框架]:管理它

[SparkCore]-->[SparkSql]:我也想写SQL(结构化数据处理)
[SparkCore]-->[SparkStreaming]:流计算
[SparkCore]-->[SparkMLlib]:机器学习
[SparkCore]-->[SparkGraphX]:图计算

@enduml